sudo: 'required'
notifications:
  email: false

services:
  - 'docker'

cache:
  directories:
    - ${HOME}/.composer/cache

branches:
  only:
  - master

before_script:
  - echo "ACF_PRO_KEY=${ACF_PRO_KEY}" > .env
  - make setup

script:
  - make lint
  - make build
  - make test_php