sudo: 'required'
notifications:
  email: false

services:
  - 'docker'

cache:
  directories:
    - ${HOME}/.composer/cache

branches:
  only:
  - master

before_script:
  - make setup

script:
  - make lint